### PR TITLE
Support numpy 2 in tests

### PR DESCRIPTION
**Pull request by cbkerr**
## Description

Apply changes from https://numpy.org/doc/stable//numpy_2_0_migration_guide.html#changes-to-namespaces

## Checklist:

- [X] I am familiar with the [Contributing Guidelines](https://github.com/glotzerlab/signac/blob/main/CONTRIBUTING.md).
- [X] I agree with the terms of the [Contributor Agreement](https://github.com/glotzerlab/signac/blob/main/ContributorAgreement.md).
- [X] My name is on the [list of contributors](https://github.com/glotzerlab/signac/blob/main/contributors.yaml).
- [X] The changes introduced by this pull request are covered by existing or newly introduced tests.
- [X] The [package documentation](https://github.com/glotzerlab/signac/tree/main/doc) and [framework documentation](https://docs.signac.io/) in [signac-docs](https://github.com/glotzerlab/signac-docs) are up to date with these changes.
- [x] I have updated the [changelog](https://github.com/glotzerlab/signac/blob/main/changelog.txt) and added any related issue and pull request numbers for future reference.

### CODE REVIEW

**Review by bdice — APPROVED** [review]

**Comment by bdice** [comment]
Test failures appear to be related to https://github.com/PyTables/PyTables/issues/1172

It's fine with me if you want to add an exception to the warnings-as-errors options in `pyproject.toml` to ignore these.

**Comment by bdice** [comment]
Overall, our dependency on PyTables has been really hard to keep working. PyTables is usually the last of signac's dependencies to support new Python versions and such. I'd be okay with softening this dependency and not requiring it in our tests. Let me know if you want more specific input on that possibility.

**Comment by cbkerr** [comment]
I see PyTables has a PR for fixing this, so I vote we wait a couple weeks and check back

**Comment by joaander** [comment]
> I see PyTables has a PR for fixing this, so I vote we wait a couple weeks and check back

The pull request on PyTables latest refactors the CI and specifically pins numpy < 2. The numpy 2 support PR has been closed and a new one has been created by an outside contributor. It appears that we will be waiting MANY weeks, if not months. 

I suggest you update the signac tests to optionally skip pytables tests so that we can move forward.

**Comment by joaander** [comment]
The failure to import pytables is a catchable `ValueErorr` exception.

The simplest fix is to use
```python
tables = pytest.importorskip("tables")
```
in place of 
```python
import tables
```
https://docs.pytest.org/en/6.2.x/reference.html#pytest.importorskip

However, it appears that exceptions other than `ModuleNotFoundError` will be considered errors in a future version of pytest: https://github.com/pytest-dev/pytest/blob/8509fe8be58ea1c093b4b0ac89382bfdacea0083/src/_pytest/outcomes.py#L288-L298

The more complex alternative is
```python
try:
    import tables
    skip_tables = False
except ValueError:
    skip_tables = True

skip_tables = pytest.mark.skipif(skip_tables,
                              reason="The tables package is non-functional.")
```
Then, decorate individual test functions (and/or classes) that use tables with:
```python
@skip_tables
```

**Review by joaander — APPROVED** [review]
Thanks!

**Pull request merged**
