### PR TITLE
Add more descriptive error if sp and id are not provided

### PR DESCRIPTION
**Pull request by cbkerr**
## Description

Adds a better error messgae for calling `project.open_job()`.

## Motivation and Context

Before, it would tell you something that implied you provided both statepoint and id: "Either statepoint or id must be provided, but not both."

I was working on something for dashboard and this more descriptive message would have saved me a little time.

## Checklist:

- [x] I am familiar with the [Contributing Guidelines](https://github.com/glotzerlab/signac/blob/main/CONTRIBUTING.md).
- [x] I agree with the terms of the [Contributor Agreement](https://github.com/glotzerlab/signac/blob/main/ContributorAgreement.md).
- [x] My name is on the [list of contributors](https://github.com/glotzerlab/signac/blob/main/contributors.yaml).
- [ ] The changes introduced by this pull request are covered by existing or newly introduced tests.
- [x] The [package documentation](https://github.com/glotzerlab/signac/tree/main/doc) and [framework documentation](https://docs.signac.io/) in [signac-docs](https://github.com/glotzerlab/signac-docs) are up to date with these changes.
- [ ] I have updated the [changelog](https://github.com/glotzerlab/signac/blob/main/changelog.txt) and added any related issue and pull request numbers for future reference.

### CODE REVIEW

**Review by mikemhenry — COMMENTED** [review]
I am in favor of improving this error message, but I am not sure if `id_none = id is None` is something I understand that well. I would rather see the None checks directly then aliasing them like that personally. I could be easily persuaded (other examples of us doing this in the codebase? Is this the pythonic way?).

**Comment by cbkerr** [comment]
> I am in favor of improving this error message, but I am not sure if `id_none = id is None` is something I understand that well. I would rather see the None checks directly then aliasing them like that personally. I could be easily persuaded (other examples of us doing this in the codebase? Is this the pythonic way?).

I defined the variables `id_none` and `statepoint_none` to only check the `is` once. But I didn't benchmark if that actually improves performance

**Comment by bdice** [comment]
> I defined the variables id_none and statepoint_none to only check the is once. But I didn't benchmark if that actually improves performance

It is very unlikely that this will improve performance, in my estimation. `x is None` is a very cheap check. Let's aim for readability and check `is None` explicitly. I'll push a commit for that.

**Comment by bdice** [comment]
@cbkerr @mikemhenry I'm happy with the changes I just pushed. If you're happy with it, feel free to approve/merge.

**Review by bdice — APPROVED** [review]

**Review by mikemhenry — APPROVED** [review]

**Pull request merged**
