### PR TITLE
Drop Support for Python 3.5

### PR DESCRIPTION
**Pull request by vishav1771**
## Description

This PR drops support for Python 3.5. I have removed CI tests, updated do and updated setup.py
## Motivation and Context
#336

## Types of Changes

- [ ] Documentation update
- [ ] Bug fix
- [x] New feature
- [x] Breaking change<sup>1</sup>

<sup>1</sup>The change breaks (or has the potential to break) existing functionality.

## Checklist:

- [x] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/signac/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/signac/blob/master/ContributorAgreement.md).
- [x] My name is on the [list of contributors](https://github.com/glotzerlab/signac/blob/master/contributors.yaml).
- [x] My code follows the [code style guideline](https://github.com/glotzerlab/signac/blob/master/CONTRIBUTING.md#code-style) of this project.
- [x] The changes introduced by this pull request are covered by existing or newly introduced tests.

If necessary:
- [x] I have updated the API documentation as part of the package doc-strings.
- [ ] I have created a separate pull request to update the [framework documentation](https://docs.signac.io/) on [signac-docs](https://github.com/glotzerlab/signac-docs) and linked it here.
- [x] I have updated the [changelog](https://github.com/glotzerlab/signac/blob/master/changelog.txt) and added all related issue and pull request numbers for future reference (if applicable). See example below.

Example for a changelog entry: `Fix issue with launching rockets to the moon (#101, #212).`

### CODE REVIEW

**Comment by bdice** [comment]
@vishav1771 I also searched the codebase and found a couple things you might have missed:

https://github.com/glotzerlab/signac/blob/842a07f644278f54c8e225e0161d64b637c6c5c7/signac/contrib/import_export.py#L546

https://github.com/glotzerlab/signac/blob/842a07f644278f54c8e225e0161d64b637c6c5c7/signac/contrib/collection.py#L925

I found these by searching the codebase for `version` and `3.*6` and `3.*5` and filtering non-matches.

Please also remove these outdated conda testing scripts, since we no longer support any Python version listed in them. 😆
- https://github.com/glotzerlab/signac/blob/master/tests/conda_create_config_host_test_env.sh
- https://github.com/glotzerlab/signac/blob/master/tests/conda_create_test_env.sh

Otherwise this looks good to me! I'll let @atravitz and @jennyfothergill review/approve/finalize. Thanks. 👍

**Comment by csadorf** [comment]
Are we planning to have no releases anymore before EOL Py3.5? Then this should not go into master. I think that in general there should be a discussion over the supported Python minor versions.

**Comment by bdice** [comment]
@csadorf I may have misunderstood your comment earlier that prompted this - I thought you were in support of dropping 3.5 because. EOL is soon, but we could make one more release if you think it is necessary. Let’s discuss adhering to NEP 29, which I linked on the other discussion.

**Comment by csadorf** [comment]
> @csadorf I may have misunderstood your comment earlier that prompted this - I thought you were in support of dropping 3.5 because. EOL is soon, but we could make one more release if you think it is necessary. Let’s discuss adhering to NEP 29, which I linked on the other discussion.

My other comment was targeted to ensure that we don't expand efforts to support Py 35 for that specific feature development.

I might have missed the other discussion. I think sticking to NEP 29 is a very good idea, but we should make that explicit somewhere. Support/non-support for Python versions must be handled very transparently both for users and developers IMO.

**Comment by mikemhenry** [comment]
Dropping python3.5 will let us update pandas to the 1.x line, but I do think we need a more discussion about what the last release will be to support python3.5

**Comment by bdice** [comment]
Following our dev meeting discussion on Monday, I will update this PR to document that we follow NEP 29. I think that is best done in the same PR but let me know if you disagree.

**Comment by csadorf** [comment]
> Following our dev meeting discussion on Monday, I will update this PR to document that we follow NEP 29. I think that is best done in the same PR but let me know if you disagree.

That's fine, no need to over-engineer.

**Comment by bdice** [comment]
I have updated this PR to document that we now follow NEP 29. @atravitz @jennyfothergill @csadorf I think it's ready for review.

**Comment by bdice** [comment]
Reviewers: ignore the failing test on pypy. This will be handled after this PR and #341 are merged.

**Pull request merged**
