### PR TITLE
deprecate Project.index

### PR DESCRIPTION
**Pull request by atravitz**
addresses issue #588 

## Motivation and Context
Indexing is deprecated and we'd like to remove `indexing.py` in v 2.0, but to do so we need to remove dependencies in `project.py`.

## Types of Changes

- [ ] Documentation update
- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change<sup>1</sup>

<sup>1</sup>The change breaks (or has the potential to break) existing functionality.

## Checklist:

- [ ] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/signac/blob/master/CONTRIBUTING.md).
- [ ] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/signac/blob/master/ContributorAgreement.md).
- [ ] My name is on the [list of contributors](https://github.com/glotzerlab/signac/blob/master/contributors.yaml).
- [ ] My code follows the [code style guideline](https://github.com/glotzerlab/signac/blob/master/CONTRIBUTING.md#code-style) of this project.
- [ ] The changes introduced by this pull request are covered by existing or newly introduced tests.

If necessary:
- [ ] I have updated the API documentation as part of the package doc-strings.
- [ ] I have created a separate pull request to update the [framework documentation](https://docs.signac.io/) on [signac-docs](https://github.com/glotzerlab/signac-docs) and linked it here.
- [ ] I have updated the [changelog](https://github.com/glotzerlab/signac/blob/master/changelog.txt) and added all related issue and pull request numbers for future reference (if applicable). See example below.

### CODE REVIEW

**Comment by atravitz** [comment]
Looks like Bradley handled dependencies etc. in #593, so I'm just adding the deprecation message here.

**Review by cbkerr — APPROVED** [review]
thanks!

**Review by bdice — APPROVED** [review]
I added a changelog line. Merging. We will still need to go back and add deprecations to individual functions accepting an `index` argument. See #588 for a list of those methods.

**Comment by atravitz** [comment]
> I added a changelog line. Merging. We will still need to go back and add deprecations to individual functions accepting an `index` argument. See #588 for a list of those methods.

@bdice I'm doing this now. Is there an easy way to only show a deprecation warning when a user passes the `index` argument? Otherwise I'll put it on all of the functions that are not already deprecated.

**Comment by bdice** [comment]
@atravitz We don't want to deprecate the whole method. Try something like this:
https://github.com/glotzerlab/signac/blob/0c5a096a11caed2d47b8bee2e1f550acc850e5e2/signac/contrib/project.py#L169

For example:
```python
# At the top of the `project.py` file:
INDEX_DEPRECATION_WARNING = "The index argument is deprecated and will be removed in signac 2.0."

# In methods with an `index` argument, put this near the top of the method:
if index is not None:
    warnings.warn(INDEX_DEPRECATION_WARNING, DeprecationWarning)

**Pull request merged**
