### PR TITLE
Group CLI commands by linking

### PR DESCRIPTION
**Pull request by cbkerr**
## Description

1. alphabetized the list of commands
2. grouped in categorize via linking at top of file for new users

## Motivation and Context

See #360

I thought it would be confusing to impose the grouping on the sidebar.
Reason 1: experienced users know what command they are looking up and alphabetical helps that.
Reason 2: new users might click on the name "Command Line Interface"  in the sidebar and be taken to the top of the page

## Types of Changes

- [x] Documentation update
- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change<sup>1</sup>

<sup>1</sup>The change breaks (or has the potential to break) existing functionality.

## Checklist:

- [x] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/signac/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/signac/blob/master/ContributorAgreement.md).
- [x] My name is on the [list of contributors](https://github.com/glotzerlab/signac/blob/master/contributors.yaml).
- [ ] My code follows the [code style guideline](https://github.com/glotzerlab/signac/blob/master/CONTRIBUTING.md#code-style) of this project.
- [ ] The changes introduced by this pull request are covered by existing or newly introduced tests.

If necessary:
- [ ] I have updated the API documentation as part of the package doc-strings.
- [ ] I have created a separate pull request to update the [framework documentation](https://docs.signac.io/) on [signac-docs](https://github.com/glotzerlab/signac-docs) and linked it here.
- [ ] I have updated the [changelog](https://github.com/glotzerlab/signac/blob/master/changelog.txt) and added all related issue and pull request numbers for future reference (if applicable). See example below.

### CODE REVIEW

**Comment by cbkerr** [comment]
(having a bit of trouble getting the commits replayed onto the master branch)

**Comment by bdice** [comment]
@cbkerr I fixed up the git history and force-pushed this branch. It was quite messy (re-ordering the CLI page left a merge conflict that was nearly impossible). Also, this branch didn't start from `master` -- it started from a previous branch that was squashed-on-merge, meaning there was no easy way to reconcile the histories. I dropped the previous branch's commits and manually re-did all the work because merging wasn't feasible. You'll want to run
```bash
git fetch
git checkout feature/cli-groups
git reset --hard origin feature/cli-groups
```
to replace your local history of the branch with the history I altered.

**Review by bdice — APPROVED** [review]
LGTM.

**Comment by bdice** [comment]
@cbkerr Please mark as ready for review, if this can be merged. It looks "done" to me but I wasn't sure if you have other work to do now that I fixed the git history.

**Comment by atravitz** [comment]
I think this is great, thanks @cbkerr !!

**Review by atravitz — APPROVED** [review]

**Pull request merged**
