### PR TITLE
Move all modules into root namespace.

### LINKED ISSUE #756: Reorganize modules for signac 2.0
The current layout of signac reflects the state of the package as it was originally conceived, i.e. as a starting point for users whose data would eventually grow into a full-sized database like MongoDB. However, experience with signac has shown that in practice most of our users stay with the job-project data model, which has become the true core of signac. Many parts of signac associated with more traditional database functionality will be removed in signac 2.0, and some of the core data structures like the JSONDict have been reimplemented in a generalized fashion in `synced_collections` (which will be spun out into its own package, see #755), so signac 2.0 will be a much leaner package than the 1.x line. For 2.0 we should reorganize our files into a flatter namespace that is more familiar to newer developers who are not familiar with or constrained by the origins of the project or its original goals.

### PR DESCRIPTION
**Pull request by bdice**
## Description
Closes #756, supersedes #862.

## Checklist:
- [x] I am familiar with the [Contributing Guidelines](https://github.com/glotzerlab/signac/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [Contributor Agreement](https://github.com/glotzerlab/signac/blob/master/ContributorAgreement.md).
- [x] My name is on the [list of contributors](https://github.com/glotzerlab/signac/blob/master/contributors.yaml).
- [x] The changes introduced by this pull request are covered by existing or newly introduced tests.
- [ ] The [package documentation](https://github.com/glotzerlab/signac/tree/master/doc) and [framework documentation](https://docs.signac.io/) in [signac-docs](https://github.com/glotzerlab/signac-docs) are up to date with these changes.
- [x] I have updated the [changelog](https://github.com/glotzerlab/signac/blob/master/changelog.txt) and added any related issue and pull request numbers for future reference.

### CODE REVIEW

**Comment by bdice** [comment]
@csadorf @vyasr I rebased the changes from #862 into this PR. Feel free to push to this branch directly.

**Comment by vyasr** [comment]
I've made two changes:
- I modified the pre-commit config to use a single global excludes pattern for `_vendor` rather than specifying it separately for each hook.
- I implemented [the first bullet point from my request on #862](https://github.com/glotzerlab/signac/pull/862#issuecomment-1328082518), moving `search_indexer.py`, `dict_manager.py`, and `utility.py` into an `_internal` subpackage. I did not move `filterparse.py` because I remembered that its functionality is leveraged by `signac-dashboard`, which means that we probably should be importing `parse_filter_args` into the top-level `signac` namespace as well. WDYT?

Assuming those changes look OK I'm happy with the current state of this PR. I would be fine with addressing any additional changes (such as the ones I proposed in #862) in follow-ups.

**Comment by bdice** [comment]
@vyasr I’m not a huge fan of an `_internal` subpackage. Nothing ties together the contents of that subpackage except API visibility, which feels odd. I’d rather keep things at the top level and start the module names with `_`. It doesn’t feel too cluttered to me.

**Comment by vyasr** [comment]
> @vyasr I’m not a huge fan of an `_internal` subpackage. Nothing ties together the contents of that subpackage except API visibility, which feels odd. I’d rather keep things at the top level and start the module names with `_`. It doesn’t feel too cluttered to me.
> 
> The pre-commit change is good! I forgot that top level excludes were possible.

Sounds good, I reverted that change and prefixed those modules with underscores.

**Review by b-butler — APPROVED** [review]
LGTM

**Comment by vyasr** [comment]
For posterity, here's what the project structure looks like now:
```
signac/
├── __init__.py
├── __main__.py
├── _dict_manager.py
├── _search_indexer.py
├── _utility.py
├── _vendor
│   ├── configobj
│   │   ├── LICENSE
│   │   ├── __init__.py
│   │   ├── _version.py
│   │   └── validate.py
│   └── deprecation
│       ├── LICENSE
│       ├── README
│       └── __init__.py
├── config.py
├── diff.py
├── errors.py
├── filterparse.py
├── h5store.py
├── hashing.py
├── import_export.py
├── job.py
├── linked_view.py
├── migration
│   ├── __init__.py
│   ├── v0_to_v1.py
│   └── v1_to_v2.py
├── project.py
├── schema.py
├── sync.py
├── syncutil.py
└── version.py
```

In the interest of quicker progress, I'm going to go ahead and merge this now. We can make further changes in subsequent PRs, and merging this now should allow us to make those changes in smaller, more self-contained PRs.

**Comment by vyasr** [comment]
@bdice the question I had about filterparse still stands. I think since dashboard is using it we should be exposing whatever functionality it needs more publicly than we are now (but that can be done in a subsequent PR).

**Pull request merged**
