### PR TITLE
Delete cov.sh

### PR DESCRIPTION
**Pull request by mikemhenry**
## Checklist:

- [x] I am familiar with the [Contributing Guidelines](https://github.com/glotzerlab/signac/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [Contributor Agreement](https://github.com/glotzerlab/signac/blob/master/ContributorAgreement.md).
- [x] My name is on the [list of contributors](https://github.com/glotzerlab/signac/blob/master/contributors.yaml).
- [x] The changes introduced by this pull request are covered by existing or newly introduced tests.
- [x] The [package documentation](https://github.com/glotzerlab/signac/tree/master/doc) and [framework documentation](https://docs.signac.io/) in [signac-docs](https://github.com/glotzerlab/signac-docs) are up to date with these changes.
- [ ] I have updated the [changelog](https://github.com/glotzerlab/signac/blob/master/changelog.txt) and added any related issue and pull request numbers for future reference.

### CODE REVIEW

**Comment by tommy-waltmann** [comment]
What does that file do and why do you want to get rid of it? It would be easier to review if I had some description and motivation/context to brief myself.

**Comment by bdice** [comment]
#845 includes this change. @mikemhenry can we close in favor of that? Should be good to go, maybe with an approval.

**Comment by bdice** [comment]
@tommy-waltmann I committed the cov.sh by accident. I used it for my own testing and it was accidentally merged.

**Comment by mikemhenry** [comment]
Also sorry for not marking this a draft, I did it during our dev meeting quickly and meant to link back to the issue with the context

**Pull request closed without merging**
