### PR TITLE
Remove doc_filter arguments in tests

### PR DESCRIPTION
**Pull request by cbkerr**
## Description

Remove `doc_filter` arguments after #586 #516.
Probably need to test deprecation before signac 2.0.

## Motivation and Context

Related to  #725.

## Checklist:

- [x] I am familiar with the [Contributing Guidelines](https://github.com/glotzerlab/signac/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [Contributor Agreement](https://github.com/glotzerlab/signac/blob/master/ContributorAgreement.md).
- [x] My name is on the [list of contributors](https://github.com/glotzerlab/signac/blob/master/contributors.yaml).
- [ ] The changes introduced by this pull request are covered by existing or newly introduced tests.
- [ ] The [package documentation](https://github.com/glotzerlab/signac/tree/master/doc) and [framework documentation](https://docs.signac.io/) in [signac-docs](https://github.com/glotzerlab/signac-docs) are up to date with these changes.
- [ ] I have updated the [changelog](https://github.com/glotzerlab/signac/blob/master/changelog.txt) and added any related issue and pull request numbers for future reference.

### CODE REVIEW

**Comment by cbkerr** [comment]
@vyas are we still planning to keep the doc_filter argument until 3.0? In that case, we should leave these tests of the new api and add tests of the proper deprecation warning.

> I made a judgment call based on known usage patterns as to when different things will be deprecated. All doc_filter arguments to methods like find_jobs are quite old and I know they are used, so preserving them until a 3.0 release makes sense (see also the discussion on https://github.com/glotzerlab/signac-docs/pull/115).
\- https://github.com/glotzerlab/signac/pull/516

**Comment by vyasr** [comment]
@cbkerr let's discuss this in the next meeting (see https://github.com/glotzerlab/signac/pull/714#discussion_r832623162).

**Comment by vyasr** [comment]
@cbkerr do you still plan to finish this up? Should we reopen?

**Comment by vyasr** [comment]
I'm going to reopen so that we don't lose track. We can close again if @cbkerr thinks we should.

**Comment by bdice** [comment]
This PR should not be needed and appears to be stale, so I'm going to close it. Here's why we don't need to make these changes:

On the current `master` branch, we are ignoring warnings about the deprecated `doc_filter`:
https://github.com/glotzerlab/signac/blob/8639ef0028be4a2ee9e7bcdb0831f4c7b22722ad/setup.cfg#L46

On `next`, we have already migrated all tests to use the unified filter syntax like `doc.a`:
https://github.com/glotzerlab/signac/blob/b4d6512ba7a6f305302e08d26cf929d6a9358dac/tests/test_project.py#L268
https://github.com/glotzerlab/signac/blob/b4d6512ba7a6f305302e08d26cf929d6a9358dac/tests/test_project.py#L862

It is intended for the `master` branch (currently major version 1) to continue using `doc_filter` arguments in its tests. The feature has not been removed from major version 1, only major version 2.

**Pull request closed without merging**
