### PR TITLE
Feature/pre commit pyupgrade

### PR DESCRIPTION
**Pull request by bdice**
## Description
I found a [pre-commit hook called pyupgrade](https://github.com/asottile/pyupgrade). It modernizes Python syntax. I configured it for 3.6+. I experimented with the tool and it seems to do a nice job, so I thought I would open a draft PR for discussion about whether this tool should be adopted. I reviewed its suggestions and all are valid.

## Motivation and Context
Pro: Helps encourage good code style for the project.
Con: Another tool that could break.

## Types of Changes
- [x] New feature

## Checklist:
- [x] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/signac/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/signac/blob/master/ContributorAgreement.md).
- [x] My name is on the [list of contributors](https://github.com/glotzerlab/signac/blob/master/contributors.yaml).
- [x] My code follows the [code style guideline](https://github.com/glotzerlab/signac/blob/master/CONTRIBUTING.md#code-style) of this project.
- [x] The changes introduced by this pull request are covered by existing or newly introduced tests.

If necessary:
- [ ] I have updated the API documentation as part of the package doc-strings.
- [ ] I have created a separate pull request to update the [framework documentation](https://docs.signac.io/) on [signac-docs](https://github.com/glotzerlab/signac-docs) and linked it here.
- [ ] I have updated the [changelog](https://github.com/glotzerlab/signac/blob/master/changelog.txt) and added all related issue and pull request numbers for future reference (if applicable). See example below.

### CODE REVIEW

**Comment by csadorf** [comment]
What's the difference to a standard linter? It doesn't just point out the issue, but also fixes it? I know many projects that have pre-commit hooks that actually run some automated code improvement prior to the commit, it usually speeds up the workflow.

**Comment by bdice** [comment]
@csadorf Good questions. Here’s the summary I am planning to give at dev meeting today:

Yes, this hook modifies code (like black, unlike flake8). Pre-commit always runs on the git staging area but never modifies the staging area. All modifications by pre-commit hook(s) become unstaged changes, which can be added.

This hook does not overlap with any other hook we currently use, as it is purely about modernization (its changes do not affect correctness). I believe all of the changes made the code simpler and more readable.

As I have become more familiar with pre-commit and linters more generally, I now have a relatively strong preference for linters and analyzers that can fix things automatically, like black and this hook for pyupgrade. I find that writing code is much faster when I can just type the lines I want and not worry about the whitespace. Let a formatter (clang-format in C++, black or yapf in Python) handle the rest. Moreover, I think hooks that automatically apply their fixes can vastly speed up PR reviews and allow a greater focus on aspects like correctness, usability, and performance (because a high standard for code style is automatically enforced).

**Comment by vyasr** [comment]
Yes, I'm a strong proponent for auto-formatters. As long as they are only format changes and guaranteed not to alter the code semantics it saves lots of wasted review iterations and ensures high code quality.

**Comment by bdice** [comment]
In dev meeting, we agreed that pyupgrade seems like a good tool and that we would also like to move towards adopting **black** in the future.

**Comment by kidrahahjo** [comment]
@bdice one question? Did this all automatically got updated or did you have to do some sort of refactorings?

**Comment by bdice** [comment]
@kidrahahjo All of the changes in this PR were performed by pyupgrade. I didn't have to do anything but `git add` and commit the changes. 😄 I did review all the changes and I think they're all safe.

**Comment by bdice** [comment]
(I accidentally closed this.)

**Review by kidrahahjo — APPROVED** [review]
Look's great

**Pull request merged**
