### PR TITLE
Move errors to signac.errors

### PR DESCRIPTION
**Pull request by b-butler**
* Deprecation warning to error modules
* core, contrib, common error modules have deprecation warning

## Description

Move all the signac specific exceptions to `signac.errors`.
## Motivation and Context

Removes code complexity and put similar functionality together.
## Types of Changes

- [ ] Documentation update
- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change<sup>1</sup>

<sup>1</sup>The change breaks (or has the potential to break) existing functionality.

## Checklist:

- [ ] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/signac/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/signac/blob/master/ContributorAgreement.md).
- [ ] My name is on the [list of contributors](https://github.com/glotzerlab/signac/blob/master/contributors.txt).
- [ ] My code follows the [code style guideline](https://github.com/glotzerlab/signac/blob/master/CONTRIBUTING.md#code-style) of this project.
- [ ] The changes introduced by this pull request are covered by existing or newly introduced tests.

If necessary:
- [ ] I have updated the API documentation as part of the package doc-strings.
- [ ] I have created a separate pull request to update the [framework documentation](https://docs.signac.io/) on [signac-docs](https://github.com/glotzerlab/signac-docs) and linked it here.
- [ ] I have updated the [changelog](https://github.com/glotzerlab/signac/blob/master/changelog.txt).

### CODE REVIEW

**Review by csadorf — COMMENTED** [review]
I do not agree that removing **all** exception classes from their respective contexts is simplifying the package code. I agree that there should probably be one central error or exception module from which most exception classes should derive from, but error classes like `WorkspaceError` do not need to be separated from the `project` module for example. I do not believe that this is standard practice either. For example, the `numpy` package defines exception classes close to the respective error context.

I would need to see more arguments in support of this change in order to be comfortable to approve it.

**Comment by csadorf** [comment]
> @csadorf I don't have too strong an opinion either way other than trying to simplify the error import logic. I see your point and would say that any error that was defined in the module where it was raised could/should stay in that module. Although I would argue that the ones defined in the subpackage error module could just be in a central error module under the direct package.

Considering that we still need to simplify the overall package structure, I might recommend that we hold off consolidating the error classes for now.

**Comment by vyasr** [comment]
I think this PR can wait until the overall package structure is simplified. The decision will be easier once we reorganize and know where all modules actually live.

**Comment by csadorf** [comment]
Closing this PR until we tackle the package reorganization.

**Pull request closed without merging**
