### PR TITLE
Misc/update citation metadata workflow

### PR DESCRIPTION
**Pull request by csadorf**
* Added CITATION.cff file.
 * Updated .zenodo.json
 * Automatic version bump for both files.
 * No automatic tagging with bumpversion.

### CODE REVIEW

**Comment by vyasr** [comment]
Is it appropriate to add the papers to the cff file?

**Comment by csadorf** [comment]
> Is it appropriate to add the papers to the cff file?

[Yes](https://citation-file-format.github.io/1.0.3/specifications/#/references-optional).

**Comment by vyasr** [comment]
OK, so we should do that before merging this in.

**Comment by csadorf** [comment]
*  [ ] Add references to `CITATION.cff`.

**Pull request merged**
