### PR TITLE
Renamed _id to id_

### LINKED ISSUE #679: Use `id_` instead of `_id`.
@vyasr [noted](https://github.com/glotzerlab/signac/pull/667#discussion_r805197076) that we use `_id` instead of `id_`: "A subsequent underscore is a more canonical way to avoid shadowing builtins, as opposed to a preceding underscore indicating a private variable."

I agree with making this change across our entire codebase in a single PR on the `next` branch before the 2.0 release. We are currently consistent about using `_id` everywhere.

For context, this is to avoid shadowing the builtin [`id`](https://docs.python.org/3/library/functions.html#id) even though `_id` disagrees with [PEP8's naming conventions](https://www.python.org/dev/peps/pep-0008/#descriptive-naming-styles) which would indicate to use `id_`.

### PR DESCRIPTION
**Pull request by rohanbabbar04**
## Description

Renamed ``_id`` to ``id_``

## Motivation and Context

Fixes #679 
Renaming ``_id`` to ``id_`` as it was an open issue

## Types of Changes

- [ ] Documentation update
- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change<sup>1</sup>
  
This is a Refactor

<sup>1</sup>The change breaks (or has the potential to break) existing functionality.

## Checklist:

- [x] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/signac/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/signac/blob/master/ContributorAgreement.md).
- [ ] My name is on the [list of contributors](https://github.com/glotzerlab/signac/blob/master/contributors.yaml).
- [x] My code follows the [code style guideline](https://github.com/glotzerlab/signac/blob/master/CONTRIBUTING.md#code-style) of this project.
- [ ] The changes introduced by this pull request are covered by existing or newly introduced tests.

If necessary:
- [ ] I have updated the API documentation as part of the package doc-strings.
- [ ] I have created a separate pull request to update the [framework documentation](https://docs.signac.io/) on [signac-docs](https://github.com/glotzerlab/signac-docs) and linked it here.
- [x] I have updated the [changelog](https://github.com/glotzerlab/signac/blob/master/changelog.txt) and added all related issue and pull request numbers for future reference (if applicable). See example below.

### CODE REVIEW

**Comment by rohanbabbar04** [comment]
@bdice Do review

**Comment by rohanbabbar04** [comment]
@bdice Do review

**Comment by bdice** [comment]
Hi @rohanbabbar04, I am going to let @vyasr review this since he is assigned. We have another open PR #681 working on this same issue, so it may be best for us to finish that existing PR and close this one.

**Comment by rohanbabbar04** [comment]
> Hi @rohanbabbar04, I am going to let @vyasr review this since he is assigned. We have another open PR #681 working on this same issue, so it may be best for us to finish that existing PR and close this one.

I guess the person is not active for more than 10 days assuming that he is not contributing as of now 
I have made this PR

**Pull request closed without merging**
