### PR TITLE
Ensure that collection file is closed. Resolves #186.

### LINKED ISSUE #186: ResourceWarning issued from unclosed file with Collection parse errors.
### Description

I noticed in the test output that there is an unclosed file when a parse error occurs while reading a Collection. In my understanding, the file is not closed because `collection._file` is never assigned, meaning that exiting the Collection's context doesn't actually close it.

```python
test_read (test_collection.FileCollectionTestBadJson) ... /home/circleci/repo/tests/test_collection.py:614: ResourceWarning: unclosed file <_io.TextIOWrapper name='/tmp/signac_collection_fdy5nu3c/test.txt' mode='r' encoding='UTF-8'>
  pass
```

### PR DESCRIPTION
**Pull request by bdice**
## Motivation and Context
Resolves unclosed file error in #186.

## Types of Changes
- [x] Bug fix

## Checklist:
- [x] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/signac/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/signac/blob/master/ContributorAgreement.md).
- [x] My name is on the [list of contributors](https://github.com/glotzerlab/signac/blob/master/contributors.txt).
- [x] My code follows the [code style guideline](https://github.com/glotzerlab/signac/blob/master/CONTRIBUTING.md#code-style) of this project.
- [x] The changes introduced by this pull request are covered by existing or newly introduced tests.

If necessary:
- [ ] I have updated the [changelog](https://github.com/glotzerlab/signac/blob/master/changelog.txt).

### CODE REVIEW

**Comment by bdice** [comment]
@csadorf I'm not sure how I would do that. Would you want to somehow ensure that a `ResourceWarning` is never raised during the execution of the tests?

**Comment by bdice** [comment]
Update: I found a way. This is an example of the warning filter I will add. https://stackoverflow.com/questions/24717027/convert-python-3-resourcewarnings-into-exception/25067818#25067818

**Comment by bdice** [comment]
I wasn't able to make this work. I imported `warnings` and edited the test as follows:

```python
    def test_read(self):
        with Collection.open(self._fn_collection, mode='r') as c:
            self.assertEqual(len(list(c)), 3)
        with open(self._fn_collection, 'a') as file:
            file.write("{'a': 0}\n")      # ill-formed JSON (single quotes instead of double quotes)
        with self.assertRaises(JSONParseError):
            with warnings.catch_warnings():
                warnings.simplefilter('error', ResourceWarning)
                with Collection.open(self._fn_collection, mode='r') as c:
                    pass
```

I got the following output:

```python
$ python test_collection.py -v FileCollectionTestBadJson.test_read
test_read (__main__.FileCollectionTestBadJson) ... test_collection.py:617: ResourceWarning: unclosed file <_io.TextIOWrapper name='/tmp/signac_collection_7dr7s4cy/test.txt' mode='r' encoding='UTF-8'>
  pass
ok

----------------------------------------------------------------------
Ran 1 test in 0.010s

OK
```

I can't get this warning to raise an error even though I directed the `warnings` module to do so in the filter. I googled for a little bit but I'm not coming up with anything helpful for resolving this.

**Comment by csadorf** [comment]
> I can't get this warning to raise an error even though I directed the warnings module to do so in the filter. I googled for a little bit but I'm not coming up with anything helpful for resolving this.

I don't see why that wouldn't work either... :/  I'm ok with cutting our losses and merge as is.

**Pull request merged**
