### PR TITLE
Add dependabot

### LINKED ISSUE #338: Automate Version Bumping With Dependabot
[Dependabot]( https://help.github.com/en/github/administering-a-repository/about-github-dependabot) can automatically a repo for the dependencies that exist, check if new versions exist, then open PRs to test and see if anything breaks. The bot also includes the release notes of the package as well, so a reviewer would need to skim the release notes to make sure there isn't anything in them that is important, then ensure that the tests pass before merging. The bot has commands to ignore a version as well as a dependency. To see an example, I've set it up on my fork here:
https://github.com/mikemhenry/signac/pulls
I set the bot up to update everything but set the max number of open PRs to 10. We could set it to only update if there are security updates if we want.

### PR DESCRIPTION
**Pull request by mikemhenry**
Fixes #338 

## Description
Sets up dependabot to update our dependency specifications every month with a maximum of 10 open PRs.

## Motivation and Context
See conversion on related issue

## Types of Changes

- [ ] Documentation update
- [ ] Bug fix
- [x] New feature
- [ ] Breaking change<sup>1</sup>

<sup>1</sup>The change breaks (or has the potential to break) existing functionality.

## Checklist:

- [x] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/signac/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/signac/blob/master/ContributorAgreement.md).
- [x] My name is on the [list of contributors](https://github.com/glotzerlab/signac/blob/master/contributors.yaml).
- [x] My code follows the [code style guideline](https://github.com/glotzerlab/signac/blob/master/CONTRIBUTING.md#code-style) of this project.
- [x] The changes introduced by this pull request are covered by existing or newly introduced tests.

If necessary:
- [ ] I have updated the API documentation as part of the package doc-strings.
- [ ] I have created a separate pull request to update the [framework documentation](https://docs.signac.io/) on [signac-docs](https://github.com/glotzerlab/signac-docs) and linked it here.
- [ ] I have updated the [changelog](https://github.com/glotzerlab/signac/blob/master/changelog.txt) and added all related issue and pull request numbers for future reference (if applicable). See example below.

Example for a changelog entry: `Fix issue with launching rockets to the moon (#101, #212).`

### CODE REVIEW

**Comment by csadorf** [comment]
@mikemhenry Looks like something went wrong with the CI tests. I'm not sure whether the pypy tests are expected to fail at the moment, but the pre-check tests should have been reported as successful. Any idea what might be going wrong?

**Comment by mikemhenry** [comment]
I'll re-run the tests, I don't expect pypy to fail... Do we run CI on a regular schedule at all? It would be nice if we re-ran the tests daily on master and had the bot bug us in slack if it fails. 

Since this PR only adds a config file, I don't expect and CI tests to fail, but I will look into it.

**Comment by bdice** [comment]
@mikemhenry It looks like the pandas issue with pypy says it needs cython to install pandas. I don't know why this would be newly appearing? We could install cython? Moving to pandas 1.x should also solve the problem because pandas has changed its packaging to include a `pyproject.toml` and no longer includes cythonized source files. We can upgrade the version after we merge #340. https://pandas.pydata.org/docs/whatsnew/v1.0.0.html?highlight=pypy#build-changes

**Comment by mikemhenry** [comment]
If we wait for dropping 3.5, it will also reduce the noise the bot generates since the 3.5 builds will fail when it tries to bump pandas. Let's wait to merge then after our next release.

**Comment by bdice** [comment]
@mikemhenry I think this is now unblocked since #340 was merged and we only support Python 3.6+.

**Comment by mikemhenry** [comment]
Okay I think this is ready to merge, our pypy build still fails but post this PR, we will get the bot to bump pandas for us.

**Comment by mikemhenry** [comment]
I can also bump the pandas version in this PR or in another if we want that taken care of ASAP

**Comment by bdice** [comment]
@mikemhenry Let's just let Dependabot bump the pandas version.

**Comment by mikemhenry** [comment]
Cool, just need one more :heavy_check_mark:  and this will be good to merge!

**Pull request merged**
