### PR TITLE
Use FutureWarning instead of DeprecationWarning in project.py

### PR DESCRIPTION
**Pull request by Onkar627**
## Description

Fixes issues as described by @vyasr in Issue #687 as we tend to change the DeprecationWarning to FutureWarning instead.
## Motivation and Context

The main motivation of this change is basically that warnings of the deprecated features are visible to the users as in current scenarios of Deprecated warnings python hides these by default.

## Types of Changes

- [ ] Documentation update
- [ ] Bug fix
- [x] New feature
- [ ] Breaking change<sup>1</sup>

<sup>1</sup>The change breaks (or has the potential to break) existing functionality.

## Checklist:

- [x] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/signac/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/signac/blob/master/ContributorAgreement.md).
- [ ] My name is on the [list of contributors](https://github.com/glotzerlab/signac/blob/master/contributors.yaml).
- [x] My code follows the [code style guideline](https://github.com/glotzerlab/signac/blob/master/CONTRIBUTING.md#code-style) of this project.
- [ ] The changes introduced by this pull request are covered by existing or newly introduced tests.

If necessary:
- [ ] I have updated the API documentation as part of the package doc-strings.
- [ ] I have created a separate pull request to update the [framework documentation](https://docs.signac.io/) on [signac-docs](https://github.com/glotzerlab/signac-docs) and linked it here.
- [ ] I have updated the [changelog](https://github.com/glotzerlab/signac/blob/master/changelog.txt) and added all related issue and pull request numbers for future reference (if applicable). See example below.

### CODE REVIEW

**Review by bdice — COMMENTED** [review]
Hi @Onkar627, thank you for the pull request! It looks like the changes in this PR are good. I have a few requests for this PR before merging:
1. An important part of the pull request process is to include descriptions of what was changed and why. Descriptions and references to related issues helps reviewers and PR authors communicate effectively. Would you be able to write some description/motivation information in the top section of the PR description? Please include a link to the issue #687. Look at past pull requests for examples of what kinds of information to write.
2. Please rename this PR to "Use `FutureWarning` instead of `DeprecationWarning` in project.py" so that the intention of the pull request is clear.
3. Look over the PR checklist and mark the appropriate boxes. For example, this PR would probably be considered a "New feature." Additionally, you need to read over and check the boxes below that to acknowledge that you have read the contributing guidelines, agree to the contributor agreement, have added yourself to the contributor list, etc.

**Comment by Onkar627** [comment]
> Hi @Onkar627, thank you for the pull request! It looks like the changes in this PR are good. I have a few requests for this PR before merging:
> 
> 1. An important part of the pull request process is to include descriptions of what was changed and why. Descriptions and references to related issues helps reviewers and PR authors communicate effectively. Would you be able to write some description/motivation information in the top section of the PR description? Please include a link to the issue #687. Look at past pull requests for examples of what kinds of information to write.
> 2. Please rename this PR to "Use `FutureWarning` instead of `DeprecationWarning` in project.py" so that the intention of the pull request is clear.
> 3. Look over the PR checklist and mark the appropriate boxes. For example, this PR would probably be considered a "New feature." Additionally, you need to read over and check the boxes below that to acknowledge that you have read the contributing guidelines, agree to the contributor agreement, have added yourself to the contributor list, etc.

Okay ,Thanks @bdice for suggestion, will keep in mind for future PR's.

**Comment by Onkar627** [comment]
I have updated the PR @bdice ,please have a look and just ping if any changes are required :)

**Comment by bdice** [comment]
@Onkar627 Thank you! If you would like, please consider adding yourself to the [list of contributors](https://github.com/glotzerlab/signac/blob/master/contributors.yaml).

I'll add a changelog entry, and then merge this PR after you add yourself to the contributor list (you may decline if you'd rather not add yourself).

**Review by bdice — APPROVED** [review]

**Comment by Onkar627** [comment]
> 

I would love to add😃.

**Comment by Onkar627** [comment]
> @Onkar627 Thank you! If you would like, please consider adding yourself to the [list of contributors](https://github.com/glotzerlab/signac/blob/master/contributors.yaml).
> 
> I'll add a changelog entry, and then merge this PR after you add yourself to the contributor list (you may decline if you'd rather not add yourself).
> 
> We will use the same changelog entry for #692, and just add the number of that PR in the same line.

Surely,I will love to add.

**Pull request merged**
