### PR TITLE
Make workspace a settable property. Define ProjectWorkspace for backwards compatibility

### LINKED ISSUE #81: Better API for the modification of configuration files
**[Original report](https://bitbucket.org/glotzer/signac/issue/81) by Carl Simon Adorf (Bitbucket: [csadorf](https://bitbucket.org/csadorf), GitHub: [csadorf](https://github.com/csadorf)).**

----------------------------------------

Modifying global, local, and project config files currently requires the use of low-level API as part of the `common.config` namespace. Manipulating the configuration should be simplified with a high-level API.

As an example, it should be possible to change the project's workspace configuration like this:
```
#!python
project.config['workspace_dir'] = '/path/to/new/workspace'
```

### PR DESCRIPTION
**Pull request by vyasr**
## Description
Makes the workspace of a project modifiable by a property API.

## Motivation and Context
Resolves #81. The config is already accessible by property, it's just the workspace that isn't yet.

I do have one question about this feature, and also the `config` property of the project. Currently any change to the config, including changing the workspace, modifies the in-memory project object, but that change will not persist beyond the current session since the underlying config file isn't updated. Considering that the command line interface for config modification updates the underlying file, and also the way that other things like statepoint/job document modification always persist to the underlying file, is that the expected behavior?

## Types of Changes

- [ ] Documentation update
- [ ] Bug fix
- [x] New feature
- [ ] Breaking change<sup>1</sup>

<sup>1</sup>The change breaks (or has the potential to break) existing functionality.

## Checklist:

- [x] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/signac/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/signac/blob/master/ContributorAgreement.md).
- [x] My name is on the [list of contributors](https://github.com/glotzerlab/signac/blob/master/contributors.yaml).
- [x] My code follows the [code style guideline](https://github.com/glotzerlab/signac/blob/master/CONTRIBUTING.md#code-style) of this project.
- [ ] The changes introduced by this pull request are covered by existing or newly introduced tests.

If necessary:
- [ ] I have updated the API documentation as part of the package doc-strings.
- [ ] I have created a separate pull request to update the [framework documentation](https://docs.signac.io/) on [signac-docs](https://github.com/glotzerlab/signac-docs) and linked it here.
- [ ] I have updated the [changelog](https://github.com/glotzerlab/signac/blob/master/changelog.txt).

### CODE REVIEW

**Comment by vyasr** [comment]
I literally just saw that this was mentioned as possibly undesirable in #239. If that is the case, I can consider alternatives for enabling this kind of feature. I do find it useful to be able to modify the workspace, but maybe there's a compromise. This doesn't immediately conflict with the suggestion there since that is a proposed future optimization, but it would preclude that optimization without making an API-breaking change so we can hold off with this PR until that's decided.

**Comment by bdice** [comment]
I think it would be totally fine to require configuration settings to be changed by the command line interface, and for configurations to be immutable once a project is instantiated in Python. Allowing project configs to change in memory is a great way to introduce potential bugs, in my opinion. Things like caches can't be used safely without a static config. If you need another workspace in Python, just create a config object and create a new Project instance from that config.

**Comment by csadorf** [comment]
Alternatively you just make the cache workspace path dependent. That would be very easy to realize. It probably would actually be critical, since we already allow an in-memory change of the configuration.

**Comment by vyasr** [comment]
@csadorf I'm not sure I follow your suggestion.

**Comment by bdice** [comment]
@csadorf Yes, incorrect caching behavior is probably already possible. I think it makes more sense to make things immutable than to enable multi-workspace caching. I benchmarked this for #239 and saw that signac spends around [~13% of its time](https://github.com/glotzerlab/signac/pull/239#issuecomment-555250864) just calling `project.workspace()`, which is silly for a value that is constant in 99.9% of real world use cases.

**Comment by csadorf** [comment]
> @csadorf Yes, incorrect caching behavior is probably already possible. I think it makes more sense to make things immutable than to enable multi-workspace caching. I benchmarked this for #239 and saw that signac spends around [~13% of its time](https://github.com/glotzerlab/signac/pull/239#issuecomment-555250864) just calling `project.workspace()`, which is silly for a value that is constant in 99.9% of real world use cases. Immutable configs would solve this.

Agreed.

**Comment by vyasr** [comment]
So what's the expected path forward? Deprecate the ability to update the project config, and remove in 2.0? And otherwise close #81 as wontfix?

**Comment by csadorf** [comment]
> So what's the expected path forward? Deprecate the ability to update the project config, and remove in 2.0? And otherwise close #81 as wontfix?

I'd think so.

**Comment by vyasr** [comment]
I'd implement that by subclassing the `Config` class (and making e.g. an `ImmutableConfig`) that for now throws a `DeprecationWarning` in `__setitem__` that will become an error in 2.0. Sound sufficient?

**Comment by vyasr** [comment]
This PR will be closed when #246 is merged.

**Comment by vyasr** [comment]
Closing, replaced by #246.

**Pull request closed without merging**
