### PR TITLE
More H5store type tests.

### PR DESCRIPTION
**Pull request by bdice**
## Description
I added some tests for additional data types to H5Store. Written while exploring #419.

## Motivation and Context
Just expands the testing suite a bit.

## Types of Changes
- [x] New feature

## Checklist:
- [x] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/signac/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/signac/blob/master/ContributorAgreement.md).
- [x] My name is on the [list of contributors](https://github.com/glotzerlab/signac/blob/master/contributors.yaml).
- [x] My code follows the [code style guideline](https://github.com/glotzerlab/signac/blob/master/CONTRIBUTING.md#code-style) of this project.
- [x] The changes introduced by this pull request are covered by existing or newly introduced tests.

### CODE REVIEW

**Comment by bdice** [comment]
@tcmoore3 @yuanzhou0827 Please review when you are able.

**Review by mikemhenry — APPROVED** [review]
LGTM!

**Comment by mikemhenry** [comment]
Hypothesis should make this even more robust when we add it.

**Comment by mikemhenry** [comment]
Given the small changes in this PR I'll merge after it passes the tests

**Pull request merged**
