### PR TITLE
Apply black and isort.

### PR DESCRIPTION
**Pull request by bdice**
## Description
This applies the linters/fixers configured in #415. Style checks should pass on this branch but not #415 

This PR exists to ease review, by separating the diff of applying #415 to all files.

The diff is huge, and reviews should focus on #415. This PR can be glanced over to get a feel for how the format looks, but I am decently confident that the formatting and other minor transformations do not affect code correctness.

## Types of Changes
- [x] giant reformat

## Checklist:
- [x] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/signac/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/signac/blob/master/ContributorAgreement.md).
- [x] My name is on the [list of contributors](https://github.com/glotzerlab/signac/blob/master/contributors.yaml).
- [x] My code follows the [code style guideline](https://github.com/glotzerlab/signac/blob/master/CONTRIBUTING.md#code-style) of this project.
- [x] The changes introduced by this pull request are covered by existing or newly introduced tests.

If necessary:
- [ ] I have updated the API documentation as part of the package doc-strings.
- [ ] I have created a separate pull request to update the [framework documentation](https://docs.signac.io/) on [signac-docs](https://github.com/glotzerlab/signac-docs) and linked it here.
- [x] I have updated the [changelog](https://github.com/glotzerlab/signac/blob/master/changelog.txt) and added all related issue and pull request numbers for future reference (if applicable). See example below.

### CODE REVIEW

**Comment by tommy-waltmann** [comment]
Is there anything other than strictly linting in this PR?

**Comment by vyasr** [comment]
I think this PR should strictly be the result of applying black and isort to all the files, nothing else.

**Review by tommy-waltmann — APPROVED** [review]

**Review by b-butler — APPROVED** [review]
Looks pretty :heart_eyes:

**Review by b-butler — COMMENTED** [review]
Although, given that we have not yet figured out the configuration fully. I will change my reviews so as to prevent premature merging.

**Review by b-butler — CHANGES_REQUESTED** [review]
Just request my review when this is done for me to approve again.

**Review by b-butler — APPROVED** [review]
Looks good.

**Pull request merged**
