### PR TITLE
Use orbs for codecov.

### LINKED ISSUE #630: Upgrade codecov: use CircleCI orb, remove deprecated Python uploader
[Codecov is deprecating](https://about.codecov.io/blog/codecov-uploader-deprecation-plan/) their bash and Python upload scripts and will disable them on February 1, 2022. We use the Python uploader to measure code coverage in several projects including signac and freud. I'm opening this issue to document my best understanding about how to proceed.

According to the [Python migration guide](https://docs.codecov.com/docs/deprecated-uploader-migration-guide#python-uploader) we'll need to execute these steps:

> 1. Remove codecov from any dependency file (e.g. requirements.txt)

For this repo, we'll remove the `pip install codecov` lines from `.circleci/config.yml`.

> 2. Replace any calls to Codecov with the new Codecov Uploader

For this repo, we'll remove the call to `codecov` and add the codecov orb: https://circleci.com/developer/orbs/orb/codecov/codecov

I'm not sure exactly how this is supposed to be called. The docs suggest addding a "job" called `codecov/upload` but it seems like it should be a step we add to an existing job...

We will need an administrator to enable 3rd party orbs in the CircleCI security settings: https://app.circleci.com/settings/organization/github/glotzerlab/security. I can enable this when we're ready to transition (tagging @joaander for awareness).

> 3. If you are using coveragepy to collect code coverage, you will need to add `coverage xml` before calling the new uploader.

We're already generating an XML output file with `pytest --cov --cov-report=xml` so no action is required for this step.

This also applies to signac-flow (@glotzerlab/signac-maintainers), signac-dashboard, freud (@glotzerlab/freud-maintainers), and garnett (@glotzerlab/garnett-maintainers).

### PR DESCRIPTION
**Pull request by vyasr**
## Description

This PR changes the way that we upload coverage results to CircleCI's new preferred method. It also changes CI so that we only upload coverage results on a single run rather than for all of them.

## Motivation and Context

Resolves #630.

## Checklist:

- [ ] I am familiar with the [Contributing Guidelines](https://github.com/glotzerlab/signac/blob/master/CONTRIBUTING.md).
- [ ] I agree with the terms of the [Contributor Agreement](https://github.com/glotzerlab/signac/blob/master/ContributorAgreement.md).
- [ ] My name is on the [list of contributors](https://github.com/glotzerlab/signac/blob/master/contributors.yaml).
- [ ] The changes introduced by this pull request are covered by existing or newly introduced tests.
- [ ] The [package documentation](https://github.com/glotzerlab/signac/tree/master/doc) and [framework documentation](https://docs.signac.io/) in [signac-docs](https://github.com/glotzerlab/signac-docs) are up to date with these changes.
- [ ] I have updated the [changelog](https://github.com/glotzerlab/signac/blob/master/changelog.txt) and added any related issue and pull request numbers for future reference.

### CODE REVIEW

**Comment by bdice** [comment]
@vyasr We need to push coverage for all CI jobs. Codecov will merge coverage reports together. We have multiple code paths (minimal dependencies vs. all optional dependencies, Linux/Mac/Windows, tests that change by Python version) and want to measure coverage across all these paths.

**Comment by bdice** [comment]
@vyasr Do you know why the codecov report / CI check isn't showing?

**Comment by vyasr** [comment]
> @vyasr We need to push coverage for all CI jobs. Codecov will merge coverage reports together. We have multiple code paths (minimal dependencies vs. all optional dependencies, Linux/Mac/Windows, tests that change by Python version) and want to measure coverage across all these paths. (Same on the signac-flow PR.)

Hmm that's a good point. It seemed a bit wasteful of CI time, but I guess it's super cheap and there are enough axes with meaningful differences (Python versions, Windows vs other) that it's probably worthwhile.

> @vyasr Do you know why the codecov report / CI check isn't showing?

Codecov doesn't usually run until all other tests pass, and Windows is failing. You can see that we do get Codecov results on the corresponding signac-flow PR where tests are passing. The multithreaded test has been failing intermittently ever since we turned on `pytest-xdist`, but I haven't been able to reproduce those failures locally. Considering how long these tests were stable prior to the xdist switch I'm not planning to spend any more time trying to debug them, so our best bet would just be to run those without parallelism. I'm open to alternate solutions if you have any though (although that's out of scope for this PR and should be done separately).

**Comment by vyasr** [comment]
I guess the issue isn't xdist. I'm not really sure what's causing this. I'm just going to disable this test on Windows. It was popping up on PyPy at one point, so if necessary I can disable that as well. If I do see that again, though, it may be worth at least one other person trying to reproduce the problem. The last time I tried, I was unable to recreate this error on my machine (a Mac) using any CPython or PyPy version.

**Comment by vyasr** [comment]
Well, we no longer have Windows hours apparently? I'm not sure what happened for us to overuse them so much, I guess too many PRs lately? In that case I'm not sure that we're going to be able to verify the results here before merging. We might just have to merge and then check that we get Codecov results in a future PR (in May once our Windows CI hours refresh).

**Comment by b-butler** [comment]
@bdice do you have any problem merging as is with Window hours being used up until May?

**Comment by bdice** [comment]
Sorry, I thought I replied on this already. 🙃 I disabled the Windows requirement in GitHub's branch protections for `master`. I am fine with ignoring Windows compatibility as a PR merge requirement as long as we check it with CI (or manually) during the release process.

I'm going to re-review this PR now.

**Review by bdice — APPROVED** [review]

**Pull request merged**
