### PR TITLE
DOC: Autoreformat doc to conform to numpydoc.

### PR DESCRIPTION
**Pull request by Carreau**
One thing which is misparsed by numpydoc is

         Returns
         -------
    -    NoneType or :class:`~signac.sync.FileTransferStats`
    +    NoneType or : class:`~signac.sync.FileTransferStats`
             Returns stats if ``collect_stats`` is ``True``, else ``None``.

Which I of course did not add; So that might be a bug in NumPyDoc.

Partial work toward #344

## Types of Changes

- [x] Documentation update
- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change<sup>1</sup>

## Checklist:

- [ ] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/signac/blob/master/CONTRIBUTING.md).
- [ ] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/signac/blob/master/ContributorAgreement.md).
- [ ] My name is on the [list of contributors](https://github.com/glotzerlab/signac/blob/master/contributors.yaml).
- [ ] My code follows the [code style guideline](https://github.com/glotzerlab/signac/blob/master/CONTRIBUTING.md#code-style) of this project.
- [ ] The changes introduced by this pull request are covered by existing or newly introduced tests.

### CODE REVIEW

**Comment by vyasr** [comment]
Hey @Carreau thanks for the PR! This looks to be a duplicate of #361, was that intentional?

**Comment by b-butler** [comment]
@Carreau should both PRs #362 and #361 be open?

**Comment by Carreau** [comment]
Let's close 361 as this one was done with a more recent version of velin; still working on the RST parsing to fix more stuff but I didn't had much time recently.

**Comment by b-butler** [comment]
Sounds good.

**Comment by csadorf** [comment]
@Carreau Did you have a chance to work on the RST parsing?

**Comment by Carreau** [comment]
> Did you have a chance to work on the RST parsing?

tiny bit but not that much. I'm going to try applying to CZI EOSS4, for a related project that might need more work on RST parsing, I've also discovered https://github.com/stsewd/tree-sitter-rst which does a fairly good job and could be reused/contributed to.

**Comment by csadorf** [comment]
@Carreau Ok, thx for the update. Let's leave the issue open then. Please let us know if we can be of any assistance.

**Comment by bdice** [comment]
I looked at a recent version of [velin](https://github.com/Carreau/velin) (which now supports being used as a pre-commit hook) but some of its suggestions weren't what I expected and might negatively impact our Sphinx docs rendering. Specifically handling of `*args`. I'm going to close this PR, we can always come back to the idea later but this PR has been stalled for long enough.

**Pull request closed without merging**
