### PR TITLE
get_statepoint deprecation error fixed

### PR DESCRIPTION
**Pull request by kidrahahjo**
## Description
Get_statepoint deprecation error fixed

## Motivation and Context
Bloated testing output signac-flow
[#224](https://github.com/glotzerlab/signac-flow/issues/244)

## Types of Changes

- [ ] Documentation update
- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change<sup>1</sup>

<sup>1</sup>The change breaks (or has the potential to break) existing functionality.

## Checklist:

- [ ] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/signac/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/signac/blob/master/ContributorAgreement.md).
- [ ] My name is on the [list of contributors](https://github.com/glotzerlab/signac/blob/master/contributors.yaml).
- [x] My code follows the [code style guideline](https://github.com/glotzerlab/signac/blob/master/CONTRIBUTING.md#code-style) of this project.
- [ ] The changes introduced by this pull request are covered by existing or newly introduced tests.

If necessary:
- [ ] I have updated the API documentation as part of the package doc-strings.
- [ ] I have created a separate pull request to update the [framework documentation](https://docs.signac.io/) on [signac-docs](https://github.com/glotzerlab/signac-docs) and linked it here.
- [ ] I have updated the [changelog](https://github.com/glotzerlab/signac/blob/master/changelog.txt) and added all related issue and pull request numbers for future reference (if applicable). See example below.

Example for a changelog entry: `Fix issue with launching rockets to the moon (#101, #212).`

### CODE REVIEW

**Comment by kidrahahjo** [comment]
@csadorf @bdice 
In reference to [#224](https://github.com/glotzerlab/signac-flow/issues/244)
When I used open_job to get the statepoint as suggested in the warning, I faced this kind of issue.

Screenshot from 2020-02-10 19-41-57

**Comment by csadorf** [comment]
@kidrahahjo I am not able to determine what the issue might be just based on the screenshot you provided. I'm afraid you will need to provide us with more information.

**Comment by csadorf** [comment]
As a side-note, I removed the review requests for both @bdice and myself. Please only requests review when the code is in a more advanced state and close to merging. Thank you.

**Comment by bdice** [comment]
@kidrahahjo It looks like you're using `open_job` in the definition of `open_job`, which is not a viable solution. Let's slow down and carefully evaluate what needs to change. A previous pull request #282 handled many of these cases, and it looks like your pull request is not based on the latest `glotzerlab:master` which should have #282 merged in. You may not need to do anything to the signac repository to resolve the warnings you're seeing in signac-flow tests -- you may only need to update your local copy of signac.

**Comment by kidrahahjo** [comment]
> @kidrahahjo It looks like you're using `open_job` in the definition of `open_job`, which is not a viable solution. Let's slow down and carefully evaluate what needs to change. A previous pull request #282 handled many of these cases, and it looks like your pull request is not based on the latest `glotzerlab:master` which should have #282 merged in. You may not need to do anything to the signac repository to resolve the warnings you're seeing in signac-flow tests -- you may only need to update your local copy of signac.

I understand that changing the code locally(in my environment) will fix the errors but shouldn't I push those changes to this repository?
I'll refer to #282 and try to avoid bad commits

**Comment by bdice** [comment]
@kidrahahjo I'm not sure if we're understanding each other. I'll try to explain what I mean.

You noticed deprecation warnings while testing signac-flow. You said [here](https://github.com/glotzerlab/signac-flow/issues/244#issuecomment-583967246) that you needed to change the signac repo to remove those deprecation warnings. However, the changes in #282 should have already fixed those deprecation warnings. I don't think this pull request is necessary.

Please try the latest `master` branch (you may need to [synchronize your fork of the repository](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork) so that `kidrahahjo:master` is up to date with `glotzerlab:master`). If you re-run signac-flow's tests after updating your version of signac to the latest master branch, the warnings about `get_statepoint` will go away (I tested this on my own machine). This kind of warning will be gone:
```
tests/test_project.py::TestExecutionProject::test_run
  /home/bdice/code/signac/signac/contrib/project.py:451: DeprecatedWarning: get_statepoint is deprecated as of 1.3 and will be removed in 2.0. Use open_job(id=jobid).statepoint() function instead.
    return self.Job(project=self, statepoint=self.get_statepoint(id), _id=id)
```

There are still other deprecated functions like the examples below, but I do not think that resolving https://github.com/glotzerlab/signac-flow/issues/244 will require changes to the signac code base, only signac-flow.

Examples of remaining deprecation warnings:
```
tests/test_project.py::TestProjectClass::test_function_in_directives
  /home/bdice/code/signac-flow/tests/test_project.py:413: DeprecatedWarning: next_operation is deprecated as of 0.8 and will be removed in 0.10. Use next_operations() instead.
    next_op = project.next_operation(job)
```
```
tests/test_project.py::TestProject::test_get_job_status
  /home/bdice/code/signac-flow/tests/test_project.py:557: DeprecatedWarning: get_id is deprecated as of 1.3 and will be removed in 2.0. Use job.id instead.
    assert status['job_id'] == job.get_id()
```

However, to resolve these deprecations, please refer to @csadorf's comment about marking tests of deprecated code (and keeping those tests until the deprecated feature is removed): https://github.com/glotzerlab/signac-flow/issues/244#issuecomment-583294999

Let me know if you agree with my assessment of this and we can close this pull request.

**Comment by kidrahahjo** [comment]
@bdice 
Yes, I now understand.
Let's close this pull request.

**Pull request closed without merging**
