### PR TITLE
Fix/deep copy issue 153

### PR DESCRIPTION
**Pull request by csadorf**
Attempt to fix issue #153 .

### CODE REVIEW

**Comment by vyasr** [comment]
We still need to decide what the expected behavior is in this case, correct? Specifically, whether or not the copied statepoint should still be associated with the original file?

**Comment by csadorf** [comment]
> We still need to decide what the expected behavior is in this case, correct? Specifically, whether or not the copied statepoint should still be associated with the original file?

I think a copied state point should be completely independent of its origin. That's how I want to and to tend use this.

**Comment by vyasr** [comment]
OK, so a deep-copied statepoint should essentially behave just like a dictionary that supports attribute-based access, but a shallow copy will still modify the underlying file? I think that's fine, but perhaps we should also update all the docstring warnings added in #154 to clarify that `copy.deepcopy` also works?

**Comment by vyasr** [comment]
@csadorf do you want to finish up this PR, or should I try and find someone else to wrap it up?

**Comment by csadorf** [comment]
> @csadorf do you want to finish up this PR, or should I try and find someone else to wrap it up?

I've been thinking a bit more about this and I believe that there is no optimal solution this. A state point is by definition not just a dict, but a dict associated with a job. Even a deep-copy should not be disassociated with the job. Users should use `_as_dict()` or `__call__()` to generate a dict from the state point.

So, in conclusion, I think we should absolutely implement copy and deepcopy explicitly, but we should not disassociate from the job class.

I'm ok with finishing this myself, but I'd appreciate a brief discussion about this.

**Comment by vyasr** [comment]
Yes, we can hold off until next week and have a brief in-person chat. I tend to agree with you, which is why I wanted to be very clear in the docs if we changed that behavior, so let's finalize next week.

**Comment by vyasr** [comment]
This PR is superseded by #207 and can be closed once that is merged.

**Comment by csadorf** [comment]
I'm going to close this now to avoid confusion.

**Pull request closed without merging**
